baseURL = "https://dtz9.com/"
defaultContentLanguage = "zh"
title = "大头针 DTZ9.COM"
theme = "hugonews"
paginate = "18"
metaDataFormat = "yaml"

[Blackfriday]
    hrefTargetBlank = "true"

[taxonomies]
    tag = "tags"
    category = "categories"
    site = "sites"    